// <auto-generated />
namespace WebShopProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropProductSizeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropProductSizeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202007151251523_DropProductSizeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
